---
title: "MSDM CEP: <span style='color: #b52b4c;'><br>Orientation for Faculty - Project Leads and Instructors</span>"
author: "Jae Min Jung, Ph.D., Professor of Marketing"
institute: "Master of Science in Digital Marketing (MSDM) Program"
date: "09/09/2026"
date-format: "M/D/YYYY"
format:
  revealjs:
    output-file: "index.html"
    #title-slide-style: pandoc
    center: false
    logo: "logos/MSDM logo horizontal-transparent.png"
    theme: [default, theme.scss]
    slide-number: true
    toc: true
    toc-depth: 1
    code-link: true
    link-external-newwindow: true
    #chalkboard: true #cannot use with self-contained
    embed-resources: true
    multiplex: true
    width: 1600
    height: 900
    margin: 0.1
    minScale: 0.2
    maxScale: 2.0
    scrollable: true
    html:
      unsafe: true
execute: 
  freeze: auto
---

# Announcement

-   Live slides available at <https://jaejungca.github.io/cep-faculty-orient/>

# Overall Agenda

::: incremental
1.  Greetings
2.  Project-Group Matching
3.  Compensation and Contract
4.  Expectations and Deliverables
    -   Fall
    -   Sprig
    -   Summer
    -   Committee chair and paperwork
5.  Meetings with Students and Client
    -   Frequency and Duration
    -   Communication and Documentation
6.  Milestones and Timelines for fall 2026
    -   Kick-off meeting: Next week
    -   Project Proposal: Week 9
    -   Final Proposal Defense: Week 15
:::

# Greetings and Introductions

-   Jae Min Jung, Ph.D., Professor of Marketing, Director of MSDM

-   All other faculty and instructors, please introduce yourself with your name, title, and affiliation.

# Project-Group Matching

# Compensation and Contract

# Expectations and Deliverables

-   Essential Documents:

    -   [MSDM Culminating Experience Project - Responsibilities for All Parties](https://www.cppmsdm.com/cep_responsibilities)

    -   [MSDM Culminating Experience Project Guide](https://www.cppmsdm.com/cep_guidelines)

    -   [MSDM CEP Main Web Page](https://www.cppmsdm.com/capstone_project)

-   [Fall](https://www.cppmsdm.com/cep_responsibilities#faculty-project-lead)

-   [Sprig](https://www.cppmsdm.com/cep_responsibilities#faculty-project-lead-1)

-   [Summer](https://www.cppmsdm.com/cep_responsibilities#sec-resp-faculty-lead-summer)

-   [Committee chair and paperwork](https://www.cppmsdm.com/capstone_project#final-edits)

    -   [Week 9](https://www.cppmsdm.com/capstone_project#final-edits)

    -   [Week 10](https://www.cppmsdm.com/capstone_project#paperwork)

# Meetings with Students and Client

-   Frequency and Duration

-   Communication and Documentation

    -   [Project Managemnet Tools](https://www.cppmsdm.com/skills_tools_courses#project-management-tools)

    -   Calendar Invite for Recurring Meetings

    -   Agendas and Minutes

# Milestones and Timelines for AY 2026-2027

## Fall Semester

+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Week / Date** | **Task**                                                                                                                                                                                  |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Su W01 (6/01)   | **Call for Project Proposal** ([Section 5](https://www.cppmsdm.com/capstone_project#sec-call-for-project-proposals))                                                                      |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Su W06 (7/06)   | **MSDM CEP Informational Session** ([Section 6](https://www.cppmsdm.com/capstone_project#sec-informational-session))                                                                      |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W00 (8/17)   | Proposal Deadline                                                                                                                                                                         |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W01 (8/24)   | Feedback provided to the proposers                                                                                                                                                        |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W02 (8/31)   | Project forum will be held in both IBM 6200 and IBM 6500                                                                                                                                  |
|                 |                                                                                                                                                                                           |
|                 | -   MSDM Project Forum I-Elevator Pitch: Group Formation                                                                                                                                  |
|                 |                                                                                                                                                                                           |
|                 | -   MSDM Project Forum II - Q&A Session: Submission of Project Preference Form (See [how to choose a project](https://www.cppmsdm.com/capstone_project#introduction))                     |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W03 (9/08)   | Project-Group Assignment Completed                                                                                                                                                        |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W04 (9/15)   | [**Project Kickoff Day (W04)**](https://www.cppmsdm.com/capstone_project#project-kickoff-day)                                                                                             |
|                 |                                                                                                                                                                                           |
|                 | -   First meeting with Faculty Lead and Client; Planning                                                                                                                                  |
|                 |                                                                                                                                                                                           |
|                 | -   For survey research, research design starts                                                                                                                                           |
|                 |                                                                                                                                                                                           |
|                 | -   For GA4 data, infrastructure setting (GA4, GTM, UTM) and verification starts                                                                                                          |
|                 |                                                                                                                                                                                           |
|                 | -   Secondary Data → Obtain it from Client. Ensure data integrity for your AO’s                                                                                                           |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W09 (10/20)  | [**Initial Proposal Presentation (W09)**](https://www.cppmsdm.com/capstone_project#initial-proposal-presentation)                                                                         |
|                 |                                                                                                                                                                                           |
|                 | -   Written report (Chapter 1, Chapter 2, and Chapter 3) / PPT due                                                                                                                        |
|                 |                                                                                                                                                                                           |
|                 | -   Survey instrument for survey research                                                                                                                                                 |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W10 (10/27)  | *Data Collection Preparation*                                                                                                                                                             |
|                 |                                                                                                                                                                                           |
|                 | -   [Primary Data Collection](https://www.cppmsdm.com/capstone_project#data-collection-primary-secondary) → **Apply for IRB** approval (takes at least 2-3 weeks for review and approval) |
|                 |                                                                                                                                                                                           |
|                 | -   [Secondary Data](https://www.cppmsdm.com/capstone_project#data-collection-primary-secondary) → Confirm **data integrity** for your AO’s                                               |
|                 |                                                                                                                                                                                           |
|                 | -   [GA4 data](https://www.cppmsdm.com/capstone_project#preparation-owned-media) → **Configure GTM**; plan for implanting **UTM** to social media & Email campaigns                       |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W12 (11/10)  | [*Data Collection Begins*](https://www.cppmsdm.com/capstone_project#data-collection)                                                                                                      |
|                 |                                                                                                                                                                                           |
|                 | -   [Primary Data Collection Methods](https://www.cppmsdm.com/capstone_project#data-collection-primary-secondary) → Primary Data Collection begins                                        |
|                 |                                                                                                                                                                                           |
|                 | -   [Secondary Data](https://www.cppmsdm.com/capstone_project#data-collection-primary-secondary) → Obtain it from Client. Ensure data integrity for your AO’s                             |
|                 |                                                                                                                                                                                           |
|                 | -   GA4 data → [GA4 data ingestion to **BigQuery**](https://www.cppmsdm.com/capstone_project#etl-tools-for-ga4-and-google-ads-data)                                                       |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W15 (12/02)  | [**Final Proposal Defense Presentation (W15)**](https://www.cppmsdm.com/capstone_project#final-proposal-defense-presentation)                                                             |
|                 |                                                                                                                                                                                           |
|                 | -   Written report (Chapter 1, Chapter 2, and Chapter 3) / PPT due                                                                                                                        |
|                 |                                                                                                                                                                                           |
|                 | -   IRB Approval Letter for survey research                                                                                                                                               |
|                 |                                                                                                                                                                                           |
|                 | -   Linked to Data saved in shared OneDrive                                                                                                                                               |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FA W16 (12/9)   | Faculty Formal Feedback to Student Groups                                                                                                                                                 |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Winter Break

+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Week / Date**             | **Task**                                                                                                                                                                             |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Winter Break (12/15 - 1/18) | -   Address faculty feedback                                                                                                                                                         |
|                             |                                                                                                                                                                                      |
|                             | -   Group should take appropriate steps necessary for them to get ready for Spring. See [Winter Break Activities](https://www.cppmsdm.com/capstone_project#winter-break-activities). |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Spring Semester

+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SP W01 (1/19) | [***Data Analysis Starts***](https://www.cppmsdm.com/capstone_project#data-analysis-starts-in-day-1-w01)                                                        |
|               |                                                                                                                                                                 |
|               | -   Data Wrangling & Visualization start;                                                                                                                       |
|               |                                                                                                                                                                 |
|               | -   Descriptive and Predictive Analytics follow                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SP W05 (2/22) | [**Data Analysis and Results Presentation (W06)**](https://www.cppmsdm.com/capstone_project#data-analysis-and-results-presentation)                             |
|               |                                                                                                                                                                 |
|               | -   Data analysis & results (Chapter 4) — written report / PPT due                                                                                              |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SP W10 (4/05) | [**Final Data Analysis and Recommendations Presentation (W13)**](https://www.cppmsdm.com/capstone_project#final-data-analysis-and-recommendations-presentation) |
|               |                                                                                                                                                                 |
|               | -   Data analysis & results (Chapter 4 & Part of Chapter 5) — written report / PPT due                                                                          |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SP W15 (5/10) | [Digital Marketing Plan Presentation (W15)](https://www.cppmsdm.com/capstone_project#digital-marketing-plan-presentation-and-start-the-campaign-immediately)    |
|               |                                                                                                                                                                 |
|               | -   Marketing Campaign Starts Immediately                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Summer Term

+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SU W01 (6/01) | [Digital Marketing Plan execution continues](https://www.cppmsdm.com/capstone_project#digital-marketing-plan-execution-continues-w01)                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SU W05 (7/02) | [**Digital Marketing Plan & Execution Progress Presentation (W05)**](https://www.cppmsdm.com/capstone_project#digital-marketing-plan-execution-progress-presentation)       |
|               |                                                                                                                                                                             |
|               | -   Chapter 5 Update — written report / PPT due                                                                                                                             |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SU W08 (7/24) | [Final presentation — DM performance assessment and reflection (W08)](https://www.cppmsdm.com/capstone_project#final-presentation-dm-performance-assessment-and-reflection) |
|               |                                                                                                                                                                             |
|               | -   Complete Chapter 5 - Written report / PPT due                                                                                                                           |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SU W09 (7/26) | [**Final Edits & Post-Presentation Activities**](https://www.cppmsdm.com/capstone_project#final-edits), including                                                           |
|               |                                                                                                                                                                             |
|               | -   Abstract                                                                                                                                                                |
|               |                                                                                                                                                                             |
|               | -   Individual Contribution Statement (ICS)                                                                                                                                 |
|               |                                                                                                                                                                             |
|               | -   Secure Committee Signature (Chair/Reader) via *Adobe Docu Process* on Graduate Studies Website.                                                                         |
|               |                                                                                                                                                                             |
|               | -   Complete CEP written report (Abstract, ICS, TOC, Ch1, Ch2, Ch3, Ch4, Ch5, Appendix, References)                                                                         |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SU W10 (8/02) | [**Paperwork**](https://www.cppmsdm.com/capstone_project#paperwork)                                                                                                         |
|               |                                                                                                                                                                             |
|               | -   Submission of Report of Culminating Experience (RCE) by Faculty Project Lead                                                                                            |
|               |                                                                                                                                                                             |
|               | -   Submission of Abstract/ICS to Library                                                                                                                                   |
|               |                                                                                                                                                                             |
|               | -   Submission of Complete Project Written Report                                                                                                                           |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

# Q&A

-   Open the floor for any questions.

# Thank You!